name: ai4life_11
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - scikit-learn
  - scikit-image
  - scipy
  - pytorch
  - torchvision
  - pip
  - pip:
    - numpy
    - matplotlib
    - pandas
    - jupyterlab
    - ipykernel
    - opencv-python
    - timm
    - git+https://github.com/facebookresearch/segment-anything.git
    - -r requirements.txt
